### ISSUE TITLE
ubuntu 22.04 lts

### ISSUE THREAD

**Issue by alenat10** [nikolaymatrosov/yc-ubuntu-xrdp-tf#1]
Hi Nikolay,
Thank you for the great template. 
I was wondering if you have an idea why changing family from "ubuntu-2004-lts" to "ubuntu-2204-lts" breaks it? With the new version the VM is up, but SSH cannot connect...

Thank you.

**Comment by nikolaymatrosov** [comment]
I have checked the terraform specification, and it works perfectly fine with the 22.04 version.

<img width="1728" alt="Screenshot 2024-11-03 at 10 41 04" src="https://github.com/user-attachments/assets/84054749-8370-445d-b0e3-92b49bff94c8">

**Comment by alenat10** [comment]
Great! Could you share the changes you made to get the result, please? I changed 2004 to 2204 in data statement (for family and resource name as well as in disk_id reference.  The VM seems to be built, but deployment stuck on ssh connection. It tries in circle and finally failed on timeout. Teh VM has 2 cores and 8GB RAM with 50% fraction.

here is the final cycle before failure:

yandex_compute_instance.xrdp-vm (remote-exec): Connecting to remote host via SSH...
yandex_compute_instance.xrdp-vm (remote-exec):   Host: x.x.x.x
yandex_compute_instance.xrdp-vm (remote-exec):   User: yc-user
yandex_compute_instance.xrdp-vm (remote-exec):   Password: false
yandex_compute_instance.xrdp-vm (remote-exec):   Private key: true
yandex_compute_instance.xrdp-vm (remote-exec):   Certificate: false
yandex_compute_instance.xrdp-vm (remote-exec):   SSH Agent: false
yandex_compute_instance.xrdp-vm (remote-exec):   Checking Host Key: false


Error: timeout - last error: SSH authentication failed (yc-user@x.x.x.x.:22): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

Thank you,
Alex

**Comment by alenat10** [comment]
Thank you for the update, Nikolay. I must be doing something wrong - I see the changed file in your repo (server.tf), replace the old one in my terraform folder and tried the deployment. Getting exactly the same issue as before - it times out on SSH connection for some reason. Works  perfectly fine with Ubuntu 2004 as you set it originally. But with the new server.tf with settings for 2204 it goes cycles trying to SSH and finally fails on timeout:

yandex_compute_instance.xrdp-vm (remote-exec): Connecting to remote host via SSH...
yandex_compute_instance.xrdp-vm (remote-exec):   Host: x.x.x.x
yandex_compute_instance.xrdp-vm (remote-exec):   User: yc-user
yandex_compute_instance.xrdp-vm (remote-exec):   Password: false
yandex_compute_instance.xrdp-vm (remote-exec):   Private key: true
yandex_compute_instance.xrdp-vm (remote-exec):   Certificate: false
yandex_compute_instance.xrdp-vm (remote-exec):   SSH Agent: false
yandex_compute_instance.xrdp-vm (remote-exec):   Checking Host Key: false
yandex_compute_instance.xrdp-vm: Still creating... [5m30s elapsed]
yandex_compute_instance.xrdp-vm: Still creating... [5m40s elapsed]


Error: timeout - last error: SSH authentication failed (yc-user@x.x.x.x:22): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
